---
language: node_js
node_js: node
node_js: [ "6", "7", "8", "9", "10", "11", "node" ]
sudo: false
script:
- npm run test
- 'if [ "$TRAVIS_NODE_VERSION" = "node" ] ; then npm run lint ; fi'
- npm run licenses
